buildscript {
    repositories {
        gradlePluginPortal()
        mavenCentral()
        google()
    }
    dependencies {
        classpath 'com.android.tools.build:gradle:9.0.0'
        classpath 'org.jetbrains.kotlin:kotlin-gradle-plugin:2.2.10'
        classpath 'org.jetbrains.kotlin:kotlin-serialization:2.2.10'
        classpath 'com.google.devtools.ksp:com.google.devtools.ksp.gradle.plugin:2.2.10-2.0.2'
    }
}

allprojects {
    repositories {
        gradlePluginPortal()
        mavenCentral()
        google()
    }
}

tasks.register('clean', Delete) {
    delete project.layout.buildDirectory
}
